//
//  FactLine.swift
//  FactApp
//
//  Created by Giorgi Gogichaishvili on 9/14/20.
//  Copyright © 2020 giorgi gogichaishvili. All rights reserved.
//

import UIKit
class FactLine
{
    var name: String
    var facts: [Fact]
    init(named: String, includeFacts: [Fact])
    {
        name = named
        facts = includeFacts
        
    }
    
    class func getFactLines() -> [FactLine]
    {
        return [Reasons(), Facts(), Results()]
    }
    // Mark: - Private Helper Methods
    private class func Reasons () -> FactLine {
        //  (1) iDevices: Apple Watch, iPad, iPhone, iOS
        var facts = [Fact]()
        
        facts.append(Fact(titled: "Reason 1", superscription: "The Treaty of Versailles - After World War I, Germany took nearly all the blame.", description: " The Treaty of Versailles - After World War I, Germany took nearly all the blame. \n\n\nThese days, historians think that all countries had a role to play in the outbreak of World War I. \n\n\nWhen World War I ended, this was not the case. \n\n\nAt the end of the War, a big meeting was held between France, England and the USA, and Germany was not allowed to go. \n\n\nOne thing they did  was decide that Germany should no longer have an army and they also had to give up valuable land with lots of resources.Germany also had to pay back lots of money to the other countries. \n\n\nThese were debts they could not afford.",imageName: "rodrigo-rodriguez-x7bbQIY6H04-unsplash"))
        facts.append(Fact(titled: "Reason 2", superscription: "People were angry - Some people were really mad about World War I and the Treaty of Versailles, especially a man called Adolf Hitler.", description: "People were angry - Some people were really mad about World War I and the Treaty of Versailles, especially a man called Adolf Hitler. \n\n\nGermany was so in debt and could not make money that they suffered from something called hyperinflation, which happened in 1923. \n\n\nSome people in Germany carried out violent uprisings (like the The Kapp Putsch) to try to overthrow the government but they did not succeed. \n\n\nHitler also tried to overthrow the government in a city called Munich. \n\n\nHitler’s uprising in 1923 was called the Munich Putsch (also called the Beer Hall Putsch). \n\n\nHowever, at this time, he wasn’t successful and he was sent to prison.", imageName: "rodrigo-rodriguez-x7bbQIY6H04-unsplash"))
        facts.append(Fact(titled: "Reason 3", superscription: "Economic Boom – The Roaring TwentiesThe economy in Germany recovered", description: "Economic Boom – The Roaring TwentiesThe economy in Germany recovered and people were really enjoying the 1920s. \n\n\nThey were having lots of fun and a man called Gustav Streseman had borrowed money from America to make the economy stronger.", imageName: "rodrigo-rodriguez-x7bbQIY6H04-unsplash"))
        facts.append(Fact(titled: "Reason 4", superscription: "Disaster strikes in 1929: the Great DepressionJust as things seemed ok, a terrible thing happened.", description: "Disaster strikes in 1929: the Great DepressionJust as things seemed ok, a terrible thing happened. \n\n\nRemember that Germany had borrowed all that money from America? Well, the American economy crashed in 1929. \n\n\nThis was called the Great Depression. \n\n\nEven though all the countries in the world suffered a little bit, Germany was hit worse because of the money they had borrowed. \n\n\nHitler and his party, the Nazi’s, really used this to their advantage. \nPeople were absolutely starving and no one had any jobs.  \n\n\nHitler also promised to fight back against the Treaty of Versailles and make Germany a great country once more.", imageName: "rodrigo-rodriguez-x7bbQIY6H04-unsplash"))
        facts.append(Fact(titled: "Reason 5", superscription: "Before World War II, Japan was also expanding their empire (the lands they had control over that belonged to other people).", description: "Before World War II, Japan was also expanding their empire (the lands they had control over that belonged to other people). \n\n\nThey did this to get more resources and materials. \n\n\nFor example, they invaded Manchuria in 1931 and China in 1937.", imageName: "rodrigo-rodriguez-x7bbQIY6H04-unsplash"))
        facts.append(Fact(titled: "Reason 6", superscription: "Hitler readies for war In 1938, Hitler started expanding the German Empire", description: "Hitler readies for war In 1938, Hitler started expanding the German Empire by taking back Austria in 1938. \n\n\nHe also took over Czechoslovakia in 1939.", imageName: "rodrigo-rodriguez-x7bbQIY6H04-unsplash"))
        return FactLine(named: "Reasons", includeFacts: facts)
    }
    
    //  (2) Mac: MacBook, MacBook Pro with Retina Display, MacBook Air, iMac
    //           Mac Pro, MacBook Pro, Mac Mini, Display, Airport Extreme,
    //           AirPort Time Capsule, AirPort Express, Magic Trackpad
    //           Magic Mouse, Apple Keyboard, Apple Battery Charger
    
    private class func Facts() -> FactLine
    {
        var facts = [Fact]()
        
        facts.append(Fact(titled: "Fact 1", superscription: "World War II began when German troops invaded Poland on 1 September 1939.", description: "World War II began when German troops invaded Poland on 1 September 1939. \n\n\nBoth France and England had promised to help Poland should it ever be attacked, and so on September 3, 1939, the two countries declared war on Germany. \n\n\nIn the months that followed, Germany troops either occupied or invaded Denmark, Norway, Belgium, the Netherlands, and eventually France.", imageName: "rodrigo-rodriguez-x7bbQIY6H04-unsplash"))
        facts.append(Fact(titled: "Fact 2", superscription: "World War II lasted...", description: "World War II lasted from 1939 to 1945.", imageName: "rodrigo-rodriguez-x7bbQIY6H04-unsplash"))
        facts.append(Fact(titled: "Fact 3", superscription: "While many countries were involved in the war..", description: "While many countries were involved in the war, they each took sides – either with the Allies, or the Axis. \n\n\nThe Allies - Great Britain, The soviet, USA. \nThe Axis - Germany, Italy, Japan", imageName: "rodrigo-rodriguez-x7bbQIY6H04-unsplash"))
        facts.append(Fact(titled: "Fact 4", superscription: "23/24 August 1939: The Molotov–Ribbentrop Pact signed.", description: "23/24 August 1939: The Molotov–Ribbentrop Pact signed. \n\n\nIts clauses provided a written guarantee of peace by each party towards the other and a commitment that declared that neither government would ally itself to or aid an enemy of the other.", imageName: "rodrigo-rodriguez-x7bbQIY6H04-unsplash"))
        facts.append(Fact(titled: "Fact 5", superscription: "After Germany sparked World War II by invading Poland in September 1939, the Schutzstaffel (SS) converted Auschwitz I, an army barracks", description: "After Germany sparked World War II by invading Poland in September 1939, the Schutzstaffel (SS) converted Auschwitz I, an army barracks, into a prisoner-of-war camp for Polish political prisoners. \n\n\nThe first inmates, German criminals brought to the camp in May 1940 as functionaries, established the camp's reputation for sadism; prisoners were beaten, tortured, and executed for the most trivial reasons. \n\n\nThe first gassings—of Soviet and Polish prisoners—took place in block 11 of Auschwitz I around August 1941. \n\n\nConstruction of Auschwitz II began the following month, and from 1942 until late 1944 freight trains delivered Jews from all over German-occupied Europe to its gas chambers. \n\n\nOf the 1.3 million people sent to Auschwitz, 1.1 million died. \nThe death toll includes 960,000 Jews (865,000 of whom were gassed on arrival), 74,000 non-Jewish Poles, 21,000 Roma, 15,000 Soviet prisoners of war, and up to 15,000 other Europeans. \n\n\nThose not gassed died of starvation, exhaustion, disease, individual executions, or beatings. Others were killed during medical experiments. \n\n\nAs the Soviet Red Army approached Auschwitz in January 1945, toward the end of the war, the SS sent most of the camp's population west on a death march to camps inside Germany and Austria. \n\n\nSoviet troops entered the camp on 27 January 1945, a day commemorated since 2005 as International Holocaust Remembrance Day.", imageName: "rodrigo-rodriguez-x7bbQIY6H04-unsplash"))
        facts.append(Fact(titled: "Fact 6", superscription: "The Battle of Britain was a major air campaign fought over southern England in the summer and autumn of 1940.", description: "The Battle of Britain was a major air campaign fought over southern England in the summer and autumn of 1940. \n\n\nAfter the evacuation of the British Expeditionary Force from Dunkirk and the Fall of France, Germany planned to gain air superiority in preparation for an invasion of Great Britain. \n\n\nDespite heavy losses, the British Royal Air Force defied the German Luftwaffe for three straight months and ultimately took the air battle to the skies above Germany. As summer turned to fall, Hitler had no choice but to call off the attack.", imageName: "rodrigo-rodriguez-x7bbQIY6H04-unsplash"))
        facts.append(Fact(titled: "Fact 7", superscription: "Japan Attacks Pearl HarborThe raid on the United States Navy base at Pearl Harbor on December 7", description: "Japan Attacks Pearl HarborThe raid on the United States Navy base at Pearl Harbor on December 7, 1941 damaged or destroyed more than 20 American ships and 300 aircraft. \n\n\nMore than 4,000 Americans were killed or wounded. The following day, the United States officially entered the war.", imageName: "rodrigo-rodriguez-x7bbQIY6H04-unsplash"))
        facts.append(Fact(titled: "Fact 8", superscription: "Battle of Midway was another major turning point in WWII. Japan’s military hoped to obliterate the United States Navy completely with a second surprise attack", description: "Battle of Midway was another major turning point in WWII. \nJapan’s military hoped to obliterate the United States Navy completely with a second surprise attack, on June 4, 1942, this time directed at the United States forces stationed on and around Midway—a small island located in the Pacific, halfway between Japan and the United States.\n\n\nUnbeknownst to Japan, however, American cryptanalysts—code breakers—had cracked Japan’s communication codes. When the battle started, United States forces were ready for it. \n\n\nJapan suffered heavy losses as a consequence and spent the remainder of the war on the defensive.", imageName: "rodrigo-rodriguez-x7bbQIY6H04-unsplash."))
        facts.append(Fact(titled: "Fact 9", superscription: "Battle of Stalingrad—The Turning Point of WW2The Battle of Stalingrad is often considered the turning point of WW2", description: "Battle of Stalingrad—The Turning Point of WW2The Battle of Stalingrad is often considered the turning point of WW2. \n\n\nIn 1942, Hitler sent an army south in an attempt to capture the Soviet Russian city that had been renamed after the Soviet leader Josef Stalin. \n\n\nThus, on July 7, started the largest, deadliest, most destructive battle ever fought in the history of warfare. The number of dead, missing, or wounded was catastrophic on both sides. \n\n\nThe German army, however, would never recover.", imageName: "rodrigo-rodriguez-x7bbQIY6H04-unsplash"))
        facts.append(Fact(titled: "Fact 10", superscription: "D-Day, the Invasion of NormandyThe plan to liberate Western Europe from Nazi control had been in the making for a long time.", description: "D-Day, the Invasion of NormandyThe plan to liberate Western Europe from Nazi control had been in the making for a long time. \n\n\nThe German army had been expecting it and had built an intricate system of defenses. \n\n\nHistorians estimate that more than 4,000 Allied soldiers were killed on June 6, 1944, alone, the first day of battle. \n\n\nStill, the attack on the German-controlled beaches of northern France was overwhelmingly successful. \nFor the first time in the war, German soldiers in Western Europe were on the retreat. \nThe end of the war was in sight.", imageName: "rodrigo-rodriguez-x7bbQIY6H04-unsplash."))
        facts.append(Fact(titled: "Fact 11", superscription: "Battle of the Bulge. ... Battle of the Bulge, also called Battle of the Ardennes", description: "Battle of the Bulge. ... Battle of the Bulge, also called Battle of the Ardennes, (December 16, 1944–January 16, 1945), the last major German offensive on the Western Front during World War II—an unsuccessful attempt to push the Allies back from German home territory.", imageName: "rodrigo-rodriguez-x7bbQIY6H04-unsplash"))
        facts.append(Fact(titled: "Fact 12", superscription: "Yalta ConferenceThe Yalta Conference, also known as the Crimea Conference and code-named Argonaut and Magneto, held 4-11 February 1945", description: "Yalta ConferenceThe Yalta Conference, also known as the Crimea Conference and code-named Argonaut and Magneto, held 4-11 February 1945, was the World War II meeting of the heads of government of the United States, the United Kingdom, and the Soviet Union to discuss the postwar reorganization of Germany and Europe.", imageName: "rodrigo-rodriguez-x7bbQIY6H04-unsplash"))
        facts.append(Fact(titled: "Fact 13", superscription: "Nazi Germany SurrendersThe final battles of fights in the battle the European Theatre of World War II as well as the German surrender to the Allies", description: "Nazi Germany SurrendersThe final battles of fights in the battle the European Theatre of World War II as well as the German surrender to the Allies took place in late April and early May 1945.", imageName: "rodrigo-rodriguez-x7bbQIY6H04-unsplash"))
        facts.append(Fact(titled: "Fact 14", superscription: "In August, the United States military dropped two atomic bombs on Japan, one over of the city of Hiroshima, the other over Nagasaki.", description: "In August, the United States military dropped two atomic bombs on Japan, one over of the city of Hiroshima, the other over Nagasaki. \n\n\nThey hoped the powerful new weapon would convince Japanese leaders to surrender quickly, It did. \nEmperor Hirohito made the announcement only a few days later over Japanese radio, and on September 2, 1945, the war that had engaged nearly every country on earth was officially over.", imageName: "rodrigo-rodriguez-x7bbQIY6H04-unsplash"))
        return FactLine(named: "Facts", includeFacts: facts)
    }
    
    //  (3) Software: OS X, iLife, iWork, Logic Pro X, Final Cut Pro X, Aperture
    
    private class func Results() -> FactLine
    {
        var facts = [Fact]()
        
        facts.append(Fact(titled: "Result 1", superscription: "World War II was the deadliest military conflict in history. An estimated total of 70–85 million people perished", description: "World War II was the deadliest military conflict in history. An estimated total of 70–85 million people perished, which was about 3% of the 1940 world population (est. 2.3 billion).[1] Deaths directly caused by the war (including military and civilians fatalities) are estimated at 50–56 million, with an additional estimated 19 to 28 million deaths from war-related disease and famine. Civilian deaths totaled 50–55 million. Military deaths from all causes totaled 21–25 million, including deaths in captivity of about 5 million prisoners of war.", imageName: "rodrigo-rodriguez-x7bbQIY6H04-unsplash"))
        facts.append(Fact(titled: "Result 2", superscription: "After the end of the war, a conference was held in Potsdam, Germany, to set up peace treaties .", description: "After the end of the war, a conference was held in Potsdam, Germany, to set up peace treaties . \n\n\nThe countries that fought with Hitler lost territory and had to pay reparations to the Allies . Germany and its capital Berlin were divided into four parts. The zones were to be controlled by Great Britain, the United States, France and the Soviet Union. \n\n\nThe three western Allies and the Soviet Union disagreed on many things and as time went on Germany was divided into two separate countries : East Germany , which had a Communist government and West Germany, which was a democratic state . \n\n\nBerlin was also divided into East and West Berlin. \n\n\nAustria was also occupied by the four Allies from 1945 to 1955.", imageName: "rodrigo-rodriguez-x7bbQIY6H04-unsplash"))
        facts.append(Fact(titled: "Result 3", superscription: "One by one, the Russians started to take over countries in eastern Europe and install Communist governments there.", description: " One by one, the Russians started to take over countries in eastern Europe and install Communist governments there. \n\n\nThe division of Europe was the beginning of the Cold War, between the democratic nations of the west and the Communist countries of eastern Europe. \n\n\nThe Iron Curtain marked the border between these two regions.", imageName: "rodrigo-rodriguez-x7bbQIY6H04-unsplash"))
        facts.append(Fact(titled: "Result 4", superscription: "After the war many Nazi leaders were arrested and punished for what they had done in the war.", description: "After the war many Nazi leaders were arrested and punished for what they had done in the war. The most famous war trials were held at Nuremberg, Germany. \n\n\nThose who were responsible for brutal crimes were sentenced to death.", imageName: "rodrigo-rodriguez-x7bbQIY6H04-unsplash"))
        facts.append(Fact(titled: "Result 5", superscription: "The biggest task was to rebuild Europe, which lay in ruins .", description: "The biggest task was to rebuild Europe, which lay in ruins . \n\n\nIn 1948 the United States set up the Marshall Plan to help Europe’s economy . \n\n\n18 nations received 13 billion dollars worth of food machines and other goods.", imageName: "rodrigo-rodriguez-x7bbQIY6H04-unsplash"))
        facts.append(Fact(titled: "Result 6", superscription: "During World War II , four of the Allied powers—the United States, Great Britain, the Soviet Union and China— agreed to create an organization that should work for peace .", description: " During World War II , four of the Allied powers—the United States, Great Britain, the Soviet Union and China— agreed to create an organization that should work for peace . \n\n\nIn April 1945 fifty countries signed a charter and gave birth to the United Nations. ", imageName: "rodrigo-rodriguez-x7bbQIY6H04-unsplash"))
        return FactLine(named: "Results", includeFacts: facts)
    }
    
    //  (4) iPod: Apple TV, iPod nano, iPod shuffle, iPod touch, iTunes
    
    

}
